# Generated by Django 5.2.6 on 2025-09-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_college_end_date_alter_college_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, upload_to='temp_files/', verbose_name="Applicant's Resume"),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Tech Stack Used'),
        ),
        migrations.AlterField(
            model_name='professionalexperience',
            name='time_duration',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Time Duration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Tech Stack Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='time_duration',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Time Duration'),
        ),
    ]
